services:
  db:
    container_name: prepopulated-db-container
    image: prepopulated-db-image
    restart: always
    networks:
      - netnet
    ports:
      - "3306:3306"

networks:
  netnet:
    name: netnet
